In [1]:
%cd ../../..

/Users/aldensio/Desktop/Projects/tourism-consultancy

In [2]:
from backend.src.supabase_retriever import supabase_retriever

In [ ]:
data = supabase_retriever.get_processed_data()

In [4]:
data

,country,month_year,num_visitors,log_visitors,month,year,is_monsoon_season,ig_sentiment,ig_sentiment_lag1,ig_sentiment_z,reddit_sentiment_z,reddit_sentiment_lag1,trip_advisor_rating,trip_advisor_rating_lag1,log_avg_currency_rate,log_avg_currency_rate_lag1,google_trend_score,google_trend_score_lag1
0,brunei,2022-02-01,9526,9.161885,2,2022,1,0.741684,0.893029,0.365570,1.117336,1.117336,4.611111,4.045455,0.853635,0.855019,1.0,1.0
1,brunei,2022-03-01,9508,9.159994,3,2022,1,0.709663,0.741684,0.261041,1.117336,1.117336,4.227273,4.611111,0.858854,0.853635,1.0,1.0
2,brunei,2022-04-01,16950,9.738082,4,2022,1,0.937762,0.709663,1.005657,1.254148,1.117336,4.300000,4.227273,0.860752,0.858854,1.0,1.0
3,brunei,2022-05-01,36487,10.504739,5,2022,0,0.528223,0.937762,-0.331262,1.390960,1.117336,4.454545,4.300000,0.867990,0.860752,1.0,1.0
4,brunei,2022-06-01,44748,10.708824,6,2022,0,0.515770,0.528223,-0.371913,0.749135,1.390960,4.470588,4.454545,0.869137,0.867990,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,vietnam,2025-01-01,2070000,14.543060,1,2025,1,0.126924,0.272369,-1.576400,-1.758921,-0.928595,4.986395,4.967320,10.138042,10.142744,54.0,17.0
403,vietnam,2025-02-01,1890000,14.452088,2,2025,1,-0.035287,0.126924,-2.211125,0.259227,-1.758921,4.991228,4.986395,10.144236,10.138042,18.0,54.0
404,vietnam,2025-03-01,1750000,14.375127,3,2025,1,-0.035287,0.126924,-2.211125,0.259227,-1.758921,4.991228,4.986395,10.147797,10.144236,19.0,18.0
405,vietnam,2025-04-01,1770000,14.386491,4,2025,1,-0.035287,0.126924,-2.211125,0.259227,-1.758921,4.991228,4.986395,10.147797,10.144236,18.0,19.0
406,vietnam,2025-05-01,1500000,14.220976,5,2025,0,-0.035287,0.126924,-2.211125,0.259227,-1.758921,4.991228,4.986395,10.147797,10.144236,18.0,19.0

In [5]:
from backend.src.model import CountryModelTrainer, CountrySplitter

In [6]:
cs = CountrySplitter()
cs.split_into_countries()

In [7]:
cmt = CountryModelTrainer()

In [8]:
import pandas as pd

singapore = pd.read_csv("backend/data/countries/singapore_final_df.csv")

In [14]:
last_five = singapore.tail(5)

In [15]:
last_five

,country,month_year,num_visitors,log_visitors,month,year,is_monsoon_season,ig_sentiment,ig_sentiment_lag1,ig_sentiment_z,reddit_sentiment_z,reddit_sentiment_lag1,trip_advisor_rating,trip_advisor_rating_lag1,log_avg_currency_rate,log_avg_currency_rate_lag1,google_trend_score,google_trend_score_lag1
32,singapore,2024-10-01,1314486,14.088957,10,2024,0,0.902282,0.918402,1.062225,0.509078,0.241871,4.303371,4.303571,0.838428,0.831388,51.0,52.0
33,singapore,2024-11-01,1234696,14.026336,11,2024,1,0.518416,0.902282,-0.048484,0.129599,0.509078,4.350427,4.303371,0.848013,0.838428,50.0,51.0
34,singapore,2024-12-01,1390631,14.145269,12,2024,1,0.402791,0.518416,-0.383044,-0.316407,0.129599,4.383721,4.350427,0.854682,0.848013,54.0,50.0
35,singapore,2025-01-01,1633471,14.306218,1,2025,1,0.831065,0.402791,0.856160,-0.939683,-0.316407,3.980000,4.383721,0.858376,0.854682,59.0,54.0
36,singapore,2025-02-01,1689200,14.339766,2,2025,1,0.147835,0.831065,-1.120754,0.619366,-0.939683,4.459770,3.980000,0.854260,0.858376,50.0,59.0

In [17]:
cmt.monitor_input_drift(
    run_id="f4e503fe0b3b4157b9d93800dc8069ce",
    new_data=last_five
)

INFO - [monitoring] starting input drift check for run_id: f4e503fe0b3b4157b9d93800dc8069ce
Downloading artifacts: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 11/11 [00:00<00:00, 554.36it/s]
INFO - [monitoring] drift check complete: 0/11 features drifted

{'is_monsoon_season': False,
 'ig_sentiment_lag1': False,
 'ig_sentiment_z': False,
 'reddit_sentiment_z': False,
 'reddit_sentiment_lag1': False,
 'trip_advisor_rating': False,
 'trip_advisor_rating_lag1': False,
 'log_avg_currency_rate': False,
 'log_avg_currency_rate_lag1': False,
 'google_trend_score': False,
 'google_trend_score_lag1': False}